<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkETnLp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkETnLp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWkETnLp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWkETnLp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWkETnLp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WkETnLp',
    'container.build_id' => 'cb710b8a',
    'container.build_time' => 1752270805,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkETnLp');
