<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'get_all_countries' => [[], ['_controller' => 'App\\Controller\\CountryController::getAll'], [], [['text', '/api/country']], [], [], []],
    'get_country_by_code' => [['code'], ['_controller' => 'App\\Controller\\CountryController::get'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'add_country' => [[], ['_controller' => 'App\\Controller\\CountryController::addCountry'], [], [['text', '/api/country']], [], [], []],
    'edit_country' => [['code'], ['_controller' => 'App\\Controller\\CountryController::edit'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'delete_country' => [['code'], ['_controller' => 'App\\Controller\\CountryController::delete'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'api_status' => [[], ['_controller' => 'App\\Controller\\StatusController::status'], [], [['text', '/api']], [], [], []],
    'api_ping' => [[], ['_controller' => 'App\\Controller\\StatusController::ping'], [], [['text', '/api/ping']], [], [], []],
    'App\Controller\CountryController::getAll' => [[], ['_controller' => 'App\\Controller\\CountryController::getAll'], [], [['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::get' => [['code'], ['_controller' => 'App\\Controller\\CountryController::get'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::addCountry' => [[], ['_controller' => 'App\\Controller\\CountryController::addCountry'], [], [['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::edit' => [['code'], ['_controller' => 'App\\Controller\\CountryController::edit'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::delete' => [['code'], ['_controller' => 'App\\Controller\\CountryController::delete'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'App\Controller\StatusController::status' => [[], ['_controller' => 'App\\Controller\\StatusController::status'], [], [['text', '/api']], [], [], []],
    'App\Controller\StatusController::ping' => [[], ['_controller' => 'App\\Controller\\StatusController::ping'], [], [['text', '/api/ping']], [], [], []],
];
